### ISSUE TITLE
jar  build   failed

### ISSUE THREAD

**Issue by zzsczz** [mdavies123/jfftw3#1]
line 70 in 

src\jfftw\planning\DirectPlan.java

        switch (complexity) {
            case COMPLEX_TO_COMPLEX -> jfftw_execute_dft(this, in, out);
            case COMPLEX_TO_REAL -> jfftw_execute_dft_c2r(this, in, out);
            case REAL_TO_COMPLEX -> jfftw_execute_dft_r2c(this, in, out);
            default -> throw new UnsupportedComplexityException(complexity);

compile  failed

**Comment by mdavies123** [comment]
This is new syntax for switch statements available as a preview in Java 12: https://blogs.oracle.com/javamagazine/post/new-switch-expressions-in-java-12

I'll change the syntax of switch statements in this project to the classic style.

**Comment by mdavies123** [comment]
Fixed with commit 769bb1d41c23a4eb5addc487bc4fcf6b2df9b4cf
